name: drama_source_core
publish_to: none
description: "追源核心库"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:

  drama_source_log:
    path: ../drama_source_log

  cat_vod:
    path: ../cat_vod

  quick_js:
    path: ../quick_js

  ok_http:
    path: ../ok_http
  # 图标
  remixicon: ^1.2.0

  # 框架、工具
  get: ^4.6.6 #状态管理、路由管理、国际化
  logger: ^2.4.0 #日志
  flutter_screenutil: ^5.9.3  #UI适配
  intl: ^0.19.0 #国际化
  uuid: ^4.4.2 #UUID
  sprintf: ^7.0.0 # 格式化
  ## JSON序列化
  json_annotation: ^4.9.0     


  # 加密
  encrypt: ^5.0.3  ## 加密算法
  convert: ^3.1.1

  
  #网络想关
  network_info_plus: ^6.0.1
  shelf_router: ^1.1.4


  #widget
  marquee: ^2.2.3 #跑马灯
  flutter_smart_dialog: ^4.9.8 #各种弹窗 Toast/Dialog/Popup
  extended_image: ^8.2.1 #拓展Image,支持缓存

  
  #系统交互
  package_info_plus: ^8.0.2 #包信息
  url_launcher: ^6.3.0 #打开链接
  path_provider: ^2.1.4 #常用路径
  device_info_plus: ^10.1.2 #设备信息
  udp: ^5.0.3 #UDP

  #视频处理
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # Native video dependencies.

  ## 数据存储
  sqflite: ^2.3.3+1            ## Android IOs
  sqflite_common_ffi: ^2.3.3  # Windows Linux MacOS


                 



dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0



flutter:
  uses-material-design: true
