name: cat_vod
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  drama_source_log:
    path: ../drama_source_log



  path_provider: ^2.1.4
  ## JSON序列化
  json_annotation: ^4.9.0

  hive: 2.2.3 #持久化存储
  hive_flutter: 1.1.0 #持久化存储

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
