name: drama_source_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  drama_source_core:
    path: ../drama_source_core
  drama_source_log:
    path: ../drama_source_log
  ok_http:
    path: ../ok_http
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  hive_flutter: ^1.1.0
  flutter_easyrefresh: 2.2.2 #下拉刷新、上拉加载
  share_plus: ^10.0.2
  tab_indicator_styler: ^2.0.0
  window_manager: ^0.4.2
  flutter_smart_dialog: ^4.9.8 #各种弹窗 Toast/Dialog/Popup
  lottie: ^1.4.3 #lottie动画


dependency_overrides: 
  fading_edge_scrollview: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21
  macos:
    generate: true


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
    - assets/js/
    - assets/images/
    - assets/images/wall/
    - assets/images/res/

